jobs:
  include:
  - stage: deploy to heroku
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: XCgJ/LG7U55TSS5vuxii173U1WC4JUEILXte8z+wieevVufkWIQR3yIt/j+NgrMereasOaa3EmoP/MySEg+zQP6RmWb0dTt1qKkIHWxQXTjWUrkLu/Jvgo90A/ltY3SpOlDmnj/dVSK3Otf6Cf02b68AuhkasBWNetu4jm5Bzu9FHudrm+1P4CF6928N+N5aQB1i+zx6RFPs0QJnRtWSNNtsXZwx3rsUS9mGOODw9pT8UQ3vxpjaHWTBqZPmJW9ng5tl1bXRI5pEhTr6tOw4+U9vfakdrrXnWc7AwHoZnF7CUf2zb9ysn67UlN3fZEnLnNhjcRD67eQunjsHw84eIb/h0wwcV1M+FasDqCLj5XLDAIIT93ExR7G9O8I14Jv9l6t1Kmc9KN30OpYToa5L1tKRckeRun0dk34nFL+tJ9Mises/nFfhQtxoW3r8sERFmrStrQa4ytkCyFdPQ9ztNH4FA7qSTg07vdsk/C9wkfD9AWBAl1YKONRaa/fpsLvASqghFbFXr7yHogM27pR9FoUcAPadCO8m24Dn5NK825U+m92aCKN8omeQJGXWQ0tJGon3/lBb33wlUMUDpVknqJIe6TOseSeuvvt/FAFOXZJumO7NLgQrF1SZAik6MWT/wqY/wWKVeZnMVhZvGZaSK/URt1XitOioFrHYPxX/4GI=
      app: medimodo
#  - stage: run ghost inspector tests
#    script: curl "https://api.ghostinspector.com/v1/suites/56f5b92519d90d942760ea96/execute/?startUrl=https://medimodo.herokuapp.com&clientId=oauth_test_client&apiKey=f5b531ccd55da08abf35fadabd7b7b04f3d64312&commit="$(git
#      rev-parse HEAD) > ghostinspector.json
#  - stage: parse test results
#    script: php ghostinspector_parser.php
