language: objective-c

node_js:
  - 5.10

sudo: false

install:
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g bower
  - npm install -g gulp

before_script:
  - npm install
  - gulp prepareQuantiModoIos

script:
  - ionic build ios
  - fastlane beta